# Generated by Django 4.0.2 on 2022-02-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210610_1442'),
        ('store', '0004_remove_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
    ]
